exports.seed = async function(knex) {
    await knex('plant_department').insert([
        {plant_id: 1, department_id: 1},
        {plant_id: 1, department_id: 2},
        {plant_id: 1, department_id: 3},
        {plant_id: 1, department_id: 4},
        {plant_id: 1, department_id: 5},
        {plant_id: 1, department_id: 6},
        {plant_id: 1, department_id: 7},
        {plant_id: 1, department_id: 8},
        {plant_id: 1, department_id: 9},
        {plant_id: 1, department_id: 10},
        {plant_id: 1, department_id: 11},
        {plant_id: 1, department_id: 13},
        {plant_id: 1, department_id: 14},
        {plant_id: 1, department_id: 15},
        {plant_id: 1, department_id: 16},
        {plant_id: 2, department_id: 1},
        {plant_id: 2, department_id: 2},
        {plant_id: 2, department_id: 3},
        {plant_id: 2, department_id: 4},
        {plant_id: 2, department_id: 5},
        {plant_id: 2, department_id: 6},
        {plant_id: 2, department_id: 7},
        {plant_id: 2, department_id: 8},
        {plant_id: 2, department_id: 9},
        {plant_id: 3, department_id: 10},
        {plant_id: 3, department_id: 11},
        {plant_id: 3, department_id: 13},
        {plant_id: 3, department_id: 14},
        {plant_id: 3, department_id: 15},
        {plant_id: 3, department_id: 16},
    ])
};
